spring.application.name=carekart-backend
server.port=8080

# Local MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/carekart

# JWT
# Change this in production. Use a long random Base64 secret.
carekart.jwt.secret=Q2FyZUthcnQtU2VjdXJlLUpXVC1LZXktRm9yLURldmVsb3BtZW50LU9ubHk=
carekart.jwt.expiration=86400000

spring.jackson.serialization.write-dates-as-timestamps=false
